### ISSUE TITLE
cargo build issue

### ISSUE THREAD

**Issue by codecandy2015** [yw662/rjson#1]
I was trying to use the rjson in my code, I am a RUST newbie, for some reason I get this error.
`
C:\dev\RUST\Workspace\rjson_example>cargo build
    Updating crates.io index
  Downloaded rjson v0.3.1
   Compiling rjson v0.3.1
error[E0554]: #![feature] may not be used on the stable release channel
 --> C:\Users\d032602\.cargo\registry\src\github.com-1ecc6299db9ec823\rjson-0.3.1\src/lib.rs:2:1
  |
2 | #![feature(alloc)]
  | ^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> C:\Users\d032602\.cargo\registry\src\github.com-1ecc6299db9ec823\rjson-0.3.1\src/lib.rs:3:1
  |
3 | #![feature(core_intrinsics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `rjson`.
`
is there some other version i need to use ?
thanks
Candy

**Comment by yw662** [comment]
Firstly, I suggest you use some other packages (if you can). The parser used in this package is not optimized (at all).

As shown in the error: `error[E0554]: #![feature] may not be used on the stable release channel`
So, you need to use nightly channel. ( or other channels that support #![feature]).
